#!/bin/bash

# Program to output a system information page

echo "<HTML>
    <HEAD>
          <TITLE>System Information Report</TITLE>
    </HEAD>
    <BODY>
           <H1> System Information Report </H1>
    </BODY>
</HTML>"
